# Generated by Django 4.1.5 on 2023-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopurban', '0002_shoploginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.IntegerField()),
                ('productdescription', models.CharField(max_length=100)),
                ('productimage', models.ImageField(upload_to='shopurban/images')),
            ],
        ),
    ]
