# Generated by Django 4.0.4 on 2023-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopurban', '0011_productuploadmodel_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('notifdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('notifdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productuploadmodel',
            name='productimage',
            field=models.ImageField(upload_to='HearHaven/static'),
        ),
    ]
