# Generated by Django 4.1.5 on 2023-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopurban', '0003_productuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadmodel',
            name='productimage',
            field=models.ImageField(upload_to='shopurban/static'),
        ),
    ]
