# Generated by Django 4.0.4 on 2023-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopurban', '0010_carddetailsmodel_delete_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadmodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
