# Generated by Django 4.0.4 on 2023-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopurban', '0012_shopnotification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
